virtualeconomy/v-wallet-gui

package.json
src/constants.js

1. update version to 0.1.3
2. change description

update version and description

---

Dockerfile

Fix "npm ERR! code ENOGIT" error in some environment

update docker script

---

src/components/home/elements/NavBar.vue
src/components/home/elements/Record.vue
src/components/home/elements/TxInfoModal.vue
src/components/home/modals/Settings.vue

Add Show CurrentBlockHeigh function

---

src/components/home/elements/LeaseRecords.vue

add more space

---

src/components/Home.vue
src/components/Warning.vue

Redirect to warning page only if cannot get block data. 
If address wrong, show "NaN".

Fix Warning Issue

---

src/components/Home.vue
src/components/home/elements/LeaseRecords.vue
src/components/home/elements/Records.vue

To resolve issue #126 
* remove duplicated get balance
* remove duplicated get TX history

remove duplicated API request

---

src/components/home/elements/TokenRecord.vue

A send-token button is added in the token record to make sending more convenient.

Add send token button

---

src/components/Home.vue
src/components/home/elements/SendToken.vue
src/components/home/elements/TokenRecord.vue
src/components/home/elements/TokenRecords.vue

The VSYS balance is check in sending token. The files transaction.js and crypto.js depend on the pr #150

check the VSYS balance when sending token

---

src/components/home/elements/BurnToken.vue
src/components/home/elements/IssueToken.vue
src/components/home/elements/SendToken.vue
src/components/home/elements/TokenRecord.vue
src/components/home/modals/NewToken.vue

the token unity is taken into account in new, issue, send, and burn token modals.
VSYS balance and input format checks are added in new, issue, send, and burn token modals.
These changes are for hot wallet only; the cold wallet has not been fixed.

#147 Display token balance fixed 

---

src/components/home/modals/NewToken.vue

add contract description and token description

---

src/components/home/elements/Record.vue
src/components/home/elements/TxInfoModal.vue

change icon for create faild

---

src/components/home/elements/LeasePane.vue
src/components/home/elements/TokenPane.vue

add margin space and delete help button

---

build/check-versions.js
package-lock.json
package.json

remove "shelljs" for security reason

remove "shelljs" package

---

package-lock.json
package.json
src/components/home/elements/LedgerWallet.vue
src/components/home/modals/CancelLease.vue
src/components/home/modals/Lease.vue
src/components/home/modals/LedgerConfirm.vue
src/components/home/modals/Send.vue
src/utils/transaction.js
src/utils/vsysLedger.js

Integrate Ledger device with Send, Lease and Cancel Leasing to Hot wallet.

function integrate with Ledger hardware device

---

src/assets/style/common.less
src/components/home/elements/Records.vue

add type filter in transaction tab

add type filter in transaction tab

---

src/components/home/elements/SplitToken.vue
src/components/home/elements/TokenRecord.vue
src/components/home/elements/WithdrawToken.vue

1.delete the function used for checking maxSupply in SplitToken
2.delete maker in WithdrawToken

Fix issues

---

src/components/home/elements/SplitToken.vue
src/components/home/elements/TokenRecord.vue

fix the bug that the unity and tokenBalance did not update until click Get Token Info

split token update issue

---

src/components/home/elements/IssueAndBurnToken.vue
src/components/home/modals/AddToken.vue

1.fix wrong destroy available and make the available number 0 when owner is not issuer
2.change add token expression

fix wrong destroy available and change add token expression

---

src/components/home/elements/SendToken.vue
src/components/home/modals/Receive.vue
src/components/home/modals/Send.vue

Invoice issue

---

src/components/home/elements/LeaseRecords.vue
src/components/home/elements/TransactionRecord.vue

Change API of Lease Tx History in Lease Tab

---

src/components/Home.vue
src/components/home/elements/TokenRecord.vue
src/components/home/elements/TransactionRecord.vue
src/components/home/elements/TxInfoModal.vue
src/components/home/modals/AddToken.vue
src/components/home/modals/NewToken.vue

Add Token in TX info modal

---

src/assets/bus.js
src/components/Home.vue
src/components/home/elements/Asset.vue
src/components/home/elements/DepositToken.vue
src/components/home/elements/IssueAndBurnToken.vue
src/components/home/elements/LeasePane.vue
src/components/home/elements/SendToken.vue
src/components/home/elements/SplitToken.vue
src/components/home/elements/Supersede.vue
src/components/home/elements/TokenPane.vue
src/components/home/elements/TokenRecord.vue
src/components/home/elements/TokenRecords.vue
src/components/home/elements/TxInfoModal.vue
src/components/home/elements/WithdrawToken.vue
src/components/home/modals/AddToken.vue
src/components/home/modals/CancelLease.vue
src/components/home/modals/Lease.vue
src/components/home/modals/NewToken.vue
src/components/home/modals/Send.vue
src/storge/index.js

Use Vuex for sending events cross components and auto refreshing balance

---

src/components/home/elements/TokenRecord.vue

add Token 'Verification' Button

---

package-lock.json
package.json
src/components/home/elements/NavBar.vue
src/components/home/elements/TokenRecord.vue
src/components/home/elements/TokenRecords.vue
src/components/home/elements/TxInfoModal.vue
src/components/home/modals/About.vue
src/components/home/modals/AddToken.vue
src/components/home/modals/NewToken.vue
src/components/home/modals/Settings.vue
src/storge/index.js

change 'Enable Advanced Function' checkbox

---

src/components/home/elements/LeasePane.vue
src/components/home/elements/NavBar.vue
src/components/home/elements/TokenInfoModal.vue
src/components/home/elements/TokenPane.vue
src/components/home/modals/TokenConfirm.vue
src/components/home/modals/TokenSuccess.vue

1、adjust the icon display
2、adjust the unity to be integer 
3、set the drop-down-item text align center

adjust some display

---

src/components/home/elements/LeaseRecords.vue
src/components/home/elements/TransactionRecords.vue

1. remove duplicated UI part in TransactionRecords.vue
2. remove duplicated UI part in LeaseRecords.vue
None
Manual tested with changing account

Duplicated ui

---

src/components/home/modals/AddToken.vue
src/utils/certify.js

Add Token with name for verified token

---

src/assets/imgs/icons/token/IPX.svg
src/components/home/elements/TokenRecord.vue
src/components/home/elements/TransactionRecord.vue
src/components/home/elements/TransactionRecords.vue
src/components/home/elements/TxInfoModal.vue
src/utils/certify.js

1. add parseFunctionData to js-v-sdk
2. parse & show verified token payment transaction
3. add certifiedTokensInfo to config
4. if token is verified and can be split, update token'unity in config when click this token related buttons in tokenRecord.
Parse & Show Verified Token payment transaction \#328
Manual testing

Parse & Show Verified Token payment transaction

---

src/components/Home.vue
src/storge/index.js

fix balance does not change

---

src/components/home/elements/SplitTokenOrSupersede.vue
src/components/home/elements/TokenRecord.vue

1、If Token do not support split, hide "Split Token" Button.
2、Unity input will be the scale bar at first. If user click "Free Input Mode", it will be text input box.

Split token ui update

---

src/App.vue
src/components/Home.vue
src/components/Login.vue
src/components/home/elements/SendToken.vue
src/components/home/elements/TokenPane.vue
src/components/home/elements/TokenRecord.vue
src/components/home/elements/TransactionRecords.vue
src/components/home/modals/Lease.vue
src/components/home/modals/Send.vue
src/storge/index.js

support redirect payment for 3rd Party

---

src/components/home/modals/AddToken.vue
src/utils/certify.js

multiple input options are supported

---

LICENSE
src/components/Login.vue
src/components/home/elements/Asset.vue
src/components/home/elements/NavBar.vue
src/components/home/elements/TxInfoModal.vue
src/components/home/modals/About.vue
src/components/home/modals/AliasAddress.vue
src/components/home/modals/Send.vue
src/components/signup/pages/CreateAccount.vue
src/constants.js
src/storge/index.js

1、add the alias address modal
2、display the alias in asset
3、support send to other address by alias

add alias address

---

src/App.vue
src/components/Home.vue
src/components/home/elements/SendToken.vue
src/components/home/elements/TokenPane.vue
src/components/home/modals/Send.vue

enhancement of redirect payment for 3rd party

---

src/components/home/elements/TxInfoModal.vue

1.add address and recipient copy button in txInfo Madal

add the copy button in txInfo Modal

---

src/components/Home.vue
src/components/home/elements/LeasePane.vue
src/components/home/elements/LeaseRecords.vue
src/components/home/elements/TransactionRecord.vue
src/components/home/modals/BatchCancelLease.vue

1、adjust cancel lease UI to support batch cancel lease

Change lease ui

---

src/components/home/modals/About.vue

update the copyright

---

src/components/Restore.vue
src/libs/seed.js

Auto correct seed for beginner in Restore Account

---

src/components/Home.vue
src/components/home/elements/Asset.vue

add address number in address list, to solve issue #381

 add address number in address list

---

src/components/Home.vue
src/components/home/elements/LeaseRecords.vue
src/components/home/elements/SendToken.vue
src/components/home/modals/Lease.vue
src/components/home/modals/LeaseInput.vue
src/components/home/modals/Send.vue
src/constants.js
src/network.js

1、add the subnode lease support enhancement raise by #376 
2、now use the https://test-rate.virtualeconomytech.com/api/superNodesDetail to test

Subnode lease support 

---

package.json
src/constants.js

update wallet version from 0.2.3 to 0.2.4

update the wallet version from 0.2.3 to 0.2.4

---

Dockerfile

Add sdk module installation script for deployment

Enhance Docker Deployment

---

src/components/home/elements/SendToken.vue
src/components/home/modals/AliasAddress.vue
src/components/home/modals/Send.vue

modify alias address logic to support any alias addresses response to issue #390

modify the alias address logic to support any alias addresses

---

src/components/home/elements/IssueOrDestroyToken.vue
src/components/home/elements/SplitTokenOrSupersede.vue
src/components/home/elements/TokenPane.vue
src/components/home/elements/TokenRecord.vue
src/components/home/elements/TransactionRecord.vue
src/components/home/elements/TransactionRecords.vue
src/components/home/elements/TxInfoModal.vue
src/components/home/elements/WithdrawOrDepositToken.vue
src/components/home/modals/CreateToken.vue
src/components/home/modals/Settings.vue
src/components/home/modals/TokenConfirm.vue
src/components/home/modals/TokenSuccess.vue
src/storge/index.js

> # PR Details
> ## Description
> * Support new contract type(payment channel and lock contact)
> * Support deposit, withdraw functions
> * Separate Contract Type
> * Re-explain contract functions
> * Support depositing/withdrawing VSYS
>
> Issue #394
> 
> 
> ## How Has This Been Tested
>  Manual tests
> 
> ## Types of changes
> * [x]   Support new contract type
> * [x]   Support deposit, withdraw functions 
> * [x]   Separate Contract Type
> * [x]   Re-explain contract functions 
> * [x]   Support depositing/withdrawing VSYS
> 
> ## Checklist
> * [x]    My code follows the code style of this project.
> * [ ]    Hot wallet test 
> * [ ]    Cold wallet test

Support New Contracts

---

package.json
src/constants.js

update version from 0.2.5 to 0.2.6

update version from 0.2.5 to 0.2.6

---

src/components/home/elements/TokenPane.vue
src/components/home/elements/TokenRecord.vue
src/components/home/elements/WithdrawOrDepositToken.vue
src/constants.js

> ## fix bugs 
> * [x]    cannot deposit token to lock contract
> * [x]    cannot withdraw token from lock contract
> #404 Cannot Deposit Token to a Lock Contract

Fix cannot deposit/withdraw token to/from lock contract, refer to issue #404

---

src/components/home/elements/IssueOrDestroyToken.vue
src/components/home/elements/SendToken.vue
src/components/home/elements/SplitTokenOrSupersede.vue
src/components/home/elements/WithdrawOrDepositToken.vue

> ## fix bugs 
> * [x]    Cannot send Token with Cold wallet
> #402 Cannot send Token with Cold wallet

fix the bug that cannot send token with cold wallet

---

src/components/Home.vue
src/components/home/elements/LeaseRecords.vue
src/components/home/elements/TransactionRecords.vue
src/components/home/modals/CreateContract.vue
src/components/home/modals/NodesManagement.vue
src/components/home/modals/Settings.vue
src/network.js
src/storge/index.js
src/utils/certify.js

> ## add Payment&&Lock contracts support
> * [x]    support register payment channel contract
> * [x]    support register lock contract
> * [x]    support hot and cold wallet
> ## node config feature
> * [x]    add node 
> * [x]    select node automatically
> #415 Cannot show Token Icon when failed to call API from explorer
> #414 Add node config feature

New features

---

src/components/home/elements/WithdrawOrDepositToken.vue
src/constants.js

> ## Show available amount for "Deposit/Withdraw" action
> * [x]    show token balance for "Deposit"
> * [x]    show contract balance for "Withdraw"
> * [x]    new UI for balance and token Id display
> #419  Show available amount for "Deposit/Withdraw" action

Contract balance

---

src/components/Home.vue
src/components/home/elements/Asset.vue
src/components/home/elements/TokenPane.vue
src/components/home/elements/TokenRecord.vue
src/storge/index.js
src/utils/browser.js

> ## Display Balance
> * [x]    modify common method `bigNumberFormatter`
> * [x]    display empty balance when network's not available

Display Balance

---

package-lock.json
package.json

remove apexcharts & electron package

remove useless package

---

src/components/home/elements/TransactionRecords.vue

Related Issue #441 Discrepancy in Airdrop Amount Reporting

fix csv bug
